#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
#---------------------------

#---------------------------
# 全局
# Global
#---------------------------

# 用于浏览器标签的图标
favicon: /img/fluid.png

# 用于苹果设备的图标
apple_touch_icon: /img/fluid.png

# 浏览器标签页中的标题分隔符
tab_title_separator: " - "

# 强制所有链接升级为 HTTPS
force_https: false

# 代码块的增强配置
code:
  copy_btn: true
  language:
    enable: true
    default: "TEXT"
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: "github gist"
      style_dark: "dark"
    prismjs:
      style: "default"
      style_dark: "tomorrow night"
      preprocess: true

# 一些好玩的功能
fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false
    scope: []
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: left
    visible: hover
    icon: ""
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    options: { showSpinner: false, trickleSpeed: 100 }

# 主题暗色模式
dark_mode:
  enable: true
  default: auto

# 主题颜色配置
color:
  body_bg_color: "#eee"
  body_bg_color_dark: "#181c27"
  navbar_bg_color: "#2f4154"
  navbar_bg_color_dark: "#1f3144"
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"
  subtitle_color: "#fff"
  subtitle_color_dark: "#d0d0d0"
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"
  board_color: "#fff"
  board_color_dark: "#252d38"
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"
  line_color: "#eaecef"
  line_color_dark: "#435266"
  scrollbar_color: "#c4c6c9"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"
  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"
  button_hover_bg_color: "#f2f3f5"
  button_hover_bg_color_dark: "#46647e"

# 主题字体配置
font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%

custom_js:
custom_css:

# 网页访问统计
web_analytics:
  enable: false
  follow_dnt: true
  baidu:
  google:
    measurement_id:
  tencent:
    sid:
    cid:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false
  umami:
    src:
    website_id:
    domains:
    start_time: 2024-01-01
    token:
    api_server:

canonical:
  enable: false

# 懒加载
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

iconfont: //at.alicdn.com/t/c/font_1736178_k526ubmyhba.css

#---------------------------
# 页头
# Header
#---------------------------

navbar:
  blog_title: "hainoir的blog"
  ground_glass:
    enable: false
    px: 3
    alpha: 0.7
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

# 搜索功能
search:
  enable: true
  path: /search.xml
  generate_path: /search.xml
  field: post
  content: true

banner:
  parallax: true
  width_height_ratio: 1.0

scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true

scroll_top_arrow:
  enable: true

open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  '
  statistics:
    enable: false
    source: "busuanzi"
  beian:
    enable: false
    icp_text: 京ICP证123456号
    police_text: 京公网安备12345678号
    police_code: 12345678
    police_icon: /img/police_beian.png

#---------------------------
# 首页
# Home Page
#---------------------------
index:
  banner_img: /img/default.png
  banner_img_height: 100
  banner_mask_alpha: 0.3
  slogan:
    enable: true
    text: "分享前端与算法知识"
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: true
  post_sticky:
    enable: true
    icon: "iconfont icon-top"

#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  default_index_img:
  meta:
    author:
      enable: false
    date:
      enable: true
      format: "LL a"
    wordcount:
      enable: true
    min2read:
      enable: true
      awl: 2
      wpm: 60
    views:
      enable: false
      source: "busuanzi"
  updated:
    enable: false
    date_format: "LL a"
    relative: false
    note_class: info
  category_bar:
    enable: true
    specific: true
    placement: left
    post_order_by: "title"
    post_limit: 0
  toc:
    enable: true
    placement: right
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0
  copyright:
    enable: true
    license: 'BY'
    author:
      enable: true
    post_date:
      enable: true
      format: "LL"
    update_date:
      enable: false
      format: "LL"
  prev_next:
    enable: true
  image_caption:
    enable: true
  image_zoom:
    enable: true
    img_url_replace: ['', '']
  footnote:
    enable: true
    header: ''
  math:
    enable: false
    specific: false
    engine: mathjax
  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }
  comments:
    enable: false
    type: disqus

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3

#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10

#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "hainoir"
  intro: "前端与算法爱好者"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/hainoir", tip: "GitHub" }

#---------------------------
# 404页
#---------------------------
page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 5000

#---------------------------
# 友链页
#---------------------------
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  items:
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
  onerror_avatar: /img/avatar.png
  custom:
    enable: false
    content: ''
  comments:
    enable: false
    type: disqus

static_prefix:
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://lib.baomitu.com/anchor-js/5.0.0/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.4/
  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/
  prismjs: https://lib.baomitu.com/prism/1.29.0/
  tocbot: https://lib.baomitu.com/tocbot/4.20.1/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  katex: https://lib.baomitu.com/KaTeX/0.16.2/
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/
  valine: https://lib.baomitu.com/valine/1.5.1/
  waline: https://registry.npmmirror.com/@waline/client/2.15.8/files/dist/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/
  twikoo: https://lib.baomitu.com/twikoo/1.6.8/
  discuss: https://lib.baomitu.com/discuss/1.2.1/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
  moment: https://lib.baomitu.com/moment.js/2.29.4/